import { useEffect, useState } from 'react';
import DashboardLayout from '../../components/layout/DashboardLayout';
import { Card, Input, Table, Alert, Spinner } from '../../components/ui';
import { financeService } from '../../services/authService';

export default function ChallanGenerationLogsPage() {
  const [logs, setLogs] = useState([]);
  const [filters, setFilters] = useState({ month_year: '' });
  const [loading, setLoading] = useState(true);
  const [err, setErr] = useState('');

  const load = () => {
    setLoading(true);
    financeService.challans.generationLogs(filters)
      .then((res) => setLogs(res.data.data || []))
      .catch((e) => setErr(e.response?.data?.message || 'Failed to load logs'))
      .finally(() => setLoading(false));
  };

  useEffect(() => { load(); }, [filters]);

  return (
    <DashboardLayout>
      <h2 className="text-2xl font-bold mb-6">Challan Generation Logs</h2>
      <Alert type="error" message={err} onClose={() => setErr('')} />
      <Card>
        <div className="mb-4">
          <Input type="month" value={filters.month_year} onChange={(e) => setFilters({ ...filters, month_year: e.target.value })} className="!mb-0 max-w-xs" placeholder="Filter by month" />
        </div>
        {loading ? <Spinner /> : (
          <Table columns={[
            { key: 'created_at', label: 'Date', render: (r) => new Date(r.created_at).toLocaleString() },
            { key: 'generation_type', label: 'Type', render: (r) => r.generation_type.replace('_', ' ') },
            { key: 'month_year', label: 'Month' },
            { key: 'class_name', label: 'Class', render: (r) => r.class_name || 'All' },
            { key: 'challans_count', label: 'Count' },
            { key: 'generated_by_name', label: 'Generated By' },
            { key: 'notes', label: 'Notes' },
          ]} data={logs} />
        )}
      </Card>
    </DashboardLayout>
  );
}
